### PR TITLE
Added caching support

### PR DESCRIPTION
**Pull request by renjfk**

### CODE REVIEW

**Comment by nilsmagnus** [comment]
Hi @renjfk, thanks for the pull-request!

Could you describe what the changes are and what features it brings? Do I have to pass some extra flags to enable/disable the caching?

**Comment by renjfk** [comment]
Hey @nilsmagnus 

Sorry for lack of explanation. It simply enables Gradle build cache which is explained [here](https://docs.gradle.org/current/userguide/build_cache.html). But currently cache key is generated based on `wsdlDir` which is not correct. It should be based on wsdlsToGenerate since they are real input sources. Let me correct that and resend changes.

**Comment by renjfk** [comment]
Hey again @nilsmagnus 

I'm not quite familiar with Gradle plugin development so lemme ask you a question if you don't mind. According to [docs](https://docs.gradle.org/current/userguide/build_cache.html#using_the_runtime_api) one can specify inputs for cache during runtime which should be roughly `inputs.files(wsdlsToGenerate.collect { it[-1] })` but it only allowed on task constructor. But then again when I try accessing `wsdlsToGenerate` inside constructor it returns `null` for some reason. Any ideas why?

**Comment by nilsmagnus** [comment]
Sorry, I don't have a clue...

**Comment by renjfk** [comment]
Couldn't figure out either but anyways, caching support can be easily enabled with following snippet as mentioned [here](https://docs.gradle.org/current/userguide/build_cache.html#enable_caching_of_non_cacheable_tasks):

```gradle
wsdl2java {
    wsdlsToGenerate = [...]
    wsdlDir = file('src/main/resources/wsdl') // normally this defaults to src/main/resources but you can override wsdlDir directory property depending where your WSDL files are located since you might have non-relevant files and that would kill the purpose of caching

    outputs.cacheIf { true }
}
```

**Pull request closed without merging**
