### PR TITLE
Refactor project for modern Gradle

### PR DESCRIPTION
**Pull request by rubengees**
This is a major refactor of the plugin to support modern Gradle versions.

The goals are:

- Latest Gradle version support (without warnings).
- Build cache support.
- Configuration avoidance.
- Explicit Kotlin support.
- Unified configuration closure (everything in `wsdl2java`).
- Near to no configuration for the user.
  - Automatic configuration of `sourceSets`.
  - Automatic adding of dependencies (`cxf` and needed ones for Java 9+ support).
- More?

##### Wsdl2JavaPlugin

- Use configuration avoidance APIs wherever possible.
- Check for Kotlin plugin(s) and make tasks depend on ours if present.
- Check for java 9+ and add necessary dependency to our `wsdl2java` configuration and the `compile` configuration.
- Hardcode the directory for the generated sources. I have not found a way to make this configurable and also give it to Kotlin plugin. This is a Gradle lifecycle problem, because the Kotlin plugin reads from the `sourceSets` before we get the setting from the user.

##### Wsdl2JavaTask

- Use the unified extension instead of individual properties.
- Make it a `@CacheableTask` (which allows Gradle's build cache to work).

##### Clean task

- Removed. Gradles default clean task takes care of it.

##### Structure

- Moved the `consumer` project into a test project under `src/test/resources/test-project` and added Gradle TestKit tests for it.
- The plugin is now a first-level project.
- Added a Kotlin test project.

**This contains at least the following breaking changes:**

- Older Gradle versions are not supported anymore. If needed, I can try to improve backwards compatibility.
- Clean task removed.
- `generatedWsdlDir` property removed and default changed.
- `wsdlDir` default changed.

### CODE REVIEW

**Comment by nilsmagnus** [comment]
Awesome! I will have a look at it later today, but this looks really good :+1:

**Comment by rubengees** [comment]
Cool, thanks!

What would be the minimum Gradle version this plugin should support? I have checked (and added tests) that we support Gradle 4.9+.
Do we need to go lower? If we do, I'd add some compat methods that check for the Gradle version and call older APIs.

**Comment by rubengees** [comment]
@nilsmagnus Friendly ping :) Did you find any time to check this?

**Comment by nilsmagnus** [comment]
Sorry for the delay :) 

LGTM, thanks for the contribution. I added you to the collaborators so you can fix minor things without my approval :)

**Comment by KrauseStefan** [comment]
This is great work!

Will await the next published release :)

**Comment by ben-manes** [comment]
This has a lot of breaking changes, no migration steps, and no changelog. Please be kinder to your users as a lot of behavior no longer works correctly in a Goovy build. I'm not exactly excited to reverse engineer your code to upgrade my usage.

**Comment by rubengees** [comment]
You are right, sorry for that.

**Pull request merged**
